name: Hardware request
title: "[Hardware Request]: "
labels: ["hardware request"]
description: "Request a new device which is not supported by this adapter"
body:
  - type: checkboxes
    attributes:
      label: I'm sure that
      options:
        - label: This device is still unsupported in the **current beta version** of this adapter
          required: true
        - label: There is no other (open) request for the same device type (used the search)
          required: true
  - type: input
    attributes:
      label: Shelly device
      description: Which device should be added?
    validations:
      required: true
  - type: input
    attributes:
      label: Original Client-ID
      description: Original Client-ID sent by the device (format: shellyxxxxxx-yyyyyy). Please mask MAC-address (yyyyyy).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output of http://<ip-address>/rpc/Shelly.GetStatus
      description: >-
        Please use your browser to retrieve information from the following web address: `http://<ip-address>/rpc/Shelly.GetStatus` and post the out put here. Replace '<ip-address>' withe the address of your shelly device.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Further information
      description: >-
        Share websites, documentation or other useful information to integrate this device
    validations:
      required: true
